name: Prepare Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - run: git config --global core.autocrlf false

      - name: Install Build Dependencies
        if: runner.os == 'linux'
        run: |
          sudo apt update
          sudo apt-get install -y \
          libopenjp2-tools \
          automake \
          libtool \
          libxext-dev \
          libxkbfile-dev \
          libxtst-dev \
          build-essential

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: npm install
        run: |
          npm install

      - name: Build/Notarize/Release Electron app
        if: startsWith(matrix.os, 'macos')
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}        
        run: |
          npm run build-publish

      - name: Build/Release Electron app
        if: startsWith(matrix.os, 'ubuntu')
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}       
        run: |
          npm run build-publish

      - name: Build/Release Electron app
        if: startsWith(matrix.os, 'windows')
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}       
        run: |
          npm run build-publish
